keep-network/sortition-pools

README.adoc, contracts/BondedSortitionPool.sol, contracts/FullyBackedSortitionPoolFactory.sol, contracts/SortitionPool.sol
We missed two things in #74:
- `BondedSortitionPool` parameters in `README`:
- `poolWeightDivisor` parameter was missing for `createSortitionPool`function,
- `memberBond` and `minimumStake` were misplaced in `selectSetGroup`.
- Comment in `BondedSortitionPool.getEligibleWeight`:
-  We are now dividing the eligible stake by pool weight divisor, not by the minimum stake.
I have additionally cleaned up Solidity linter warnings.
Refs: keep-network/keep-ecdsa#302
=> Minimum stake schedule updates - cleanup

package-lock.json, package.json
`v0.3.0-rc` will contain:
- Minimum stake schedule support (#74, #78)
- Bump Solidity to 0.5.17 and freeze version (#76)
- Dependency security fix update (#77)
=> Bumping up version for 0.3.0 release

contracts/SortitionTree.sol, contracts/api/IBondedSortitionPool.sol, contracts/api/ISortitionPool.sol
This pull request makes `totalWeight` function public in order to allow getting the total weight of the sortition pool by external clients.
=> Expose totalWeight function

contracts/BondedSortitionPool.sol, test/bondedSortitionPoolTest.js
Refs: https://github.com/keep-network/keep-ecdsa/issues/506
`BondedSortitionPool` was updating the minimum bondable value for each `selectSetGroup` call. The idea was to automatically remove from the pool operators that are no longer able to satisfy application needs about the minimum available bondable value and prevent operators with too low value griefing signer selection.
We now have two minimum bond values: one defining the minimum unbonded value the operator needs to have so that it can join and stay in the pool, and another defining the required bond value for the current selection. If the given operator has enough unbonded value to stay in the pool but it does not have enough unbonded value for the current group selection, it is skipped.
We assume a reasonable minimum bondable …
=> Minimum bondable value for pool and bond value for the current selection

contracts/RNG.sol
Addressing two issues reported by Slither:
```
RNG.bitsRequired(uint256) (RNG.sol#137-155) contains a tautology or contradiction:
- bits >= 0 (RNG.sol#140)
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#tautology-or-contradiction
```
Addressed in d7025e2 by refacoring the loop. The loop should work exactly the same as before except that we avoid the
comparison of `bits >= 0` which is always `true` because `bits` is an `uint`.
```
RNG.getIndex(uint256,bytes32).index (RNG.sol#200) is a local variable never initialized
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#uninitialized-local-variables
```
Addressed in 5588f31 by initializing the `index`. It does not change how the function works and, in
fact, index, when not initialized, is …
=> Small loop refactor to make Slither happier

contracts/Leaf.sol
`Leaf` library has `operator`, `creationBlock`, and `weight` functions and they were shadowed in `make` function by input parameters with the same name. Added underscores to parameter names to avoid shadowing.
=> Renamed input parameters to Leaf.make function to avoid shadowing

package-lock.json, package.json
The new release will contain no functionality changes but will re-organize the code based on Linter and Slither suggestions:
- Update linting configuration https://github.com/keep-network/sortition-pools/pull/87
- Small loop refactor to make Slither happier https://github.com/keep-network/sortition-pools/pull/90
- Renamed input parameters to Leaf.make function to avoid shadowing https://github.com/keep-network/sortition-pools/pull/91
See https://github.com/keep-network/sortition-pools/milestone/4?closed=1
=> Bumping up version to 1.1.1 for a new release

.github/workflows/solidity-test.yml, buidler.config.js, package-lock.json, package.json
> [**Paul Bunyan** is a giant lumberjack and folk hero in American[2] and Canadian folklore.[3] His exploits revolve around the tall tales of his superhuman labors,[4][5] and he is customarily accompanied by **Babe the Blue Ox**.](https://en.wikipedia.org/wiki/Paul_Bunyan)
Log away, folks.
This PR allows the usage of buidler-vm instead of ganache for testing,
which in turn allows the usage of console.log in contracts.
A special script, `buidler-vm:log`, filters the buidler VM output to only
log output. This is useful for testing with logs.
Lastly, with ganache gone, its script is updated to note that Ganache
is no longer used, and the Solidity test workflow is updated to use
npm run buidler-vm instead of ganache.
-------
To use logging in a contract, add an import:
```
import …
```
=> Babe the Blue Ox: Add rudimentary buidler setup

contracts/RNG.sol, test/contracts/BondingContractStub.sol, test/contracts/StakingContractStub.sol, test/rngTest.js, test/workDistributionTest.js
The `RNG` was using the `POSITION_BITS` to determine how many total bits can be used in a pool index. This limited the RNG's range to the total number of positions in the pool, rather than the total weight the pool could manage. In previous usage, this was sufficient for total weight as well, but since the system has since moved to handling ETH fully backed pools and denominate KEEP stakes by individual tokens instead of minstakes, the ~2M position limit is no longer sufficient to represent the magnitude of total weights that need to be handled.
In addition to this fix, we are adding two tests for `BondedSortitionPool` and two tests for `FullyBackedSortitionPool` covering the distribution of `selectSetGroup` results.
For `BondedSortitionPool` we are making sure that `selectSetGroup` …
=> Use WEIGHT_WIDTH to index full weight range in RNG 

package-lock.json, package.json
The new release will contain two changes:
- Use WEIGHT_WIDTH to index full weight range in RNG  #94 
- Babe the Blue Ox: Add rudimentary buidler setup #93 
See https://github.com/keep-network/sortition-pools/milestone/5?closed=1
=> Bumping up version to 1.1.2 for a new release

contracts/FullyBackedSortitionPool.sol, test/fullyBackedSortitionPoolTest.js
Added functionality of operators banning in FullyBackedSortitionPool contract.
A pool owner can call a function to ban an operator. Once an operator gets banned it is removed from the pool. The operator won't get selected to new groups.
An operator can be banned even if it has never been registered or is not currently registered in the pool.
A banned operator cannot join a pool.
Depends on https://github.com/keep-network/sortition-pools/pull/89
Depends on https://github.com/keep-network/sortition-pools/pull/97
Refs keep-network/keep-ecdsa#483
=> Ban operator in FullyBackedSortitionPool

.github/workflows/npm.yml, .npmrc, package-lock.json, package.json
Here we update script for publishing NPM package in GitHub Actions job.
For `master` branch we want to publish `pre` package on each `master`
merge. But there is no sense in doing so if nothing has changed in the
solidity contracts. Circle CI doesn't allow us to filter on changed
content to run a job, that's why we use GitHub Actions. We will publish
new `pre` package to NPM registry on master merge only if solidity
contracts have changed.
Publishing to NPM registry requires a `NPM_TOKEN` token to be configured
in GH project's secrets variables.
Refs: keep-network/keep-ecdsa#659
=> Updated GitHub action for NPM package publication

.github/workflows/npm.yml
Workflow has been modified to look similiar to `NPM` workflows in
`keep-core` and `keep-ecdsa`. The main change is switching to use of
`npm-version-bump` action.
=> Unify `NPM` workflow with `NPM` workflows in other projects

package-lock.json, package.json
`-dev` suffix will be used for the versioning of the `sortition-pools`
package built with the purpose of being used on development environment.
Packages with the `-dev`-suffix will be pushed to the NPM registry by
the `NPM` GH Actions workflow.
Note that packages ment for the test environment (Ropsten) will be
versioned independently, based on the suffix provided during manual
triggering of the `Main` workflow in `ci` project.
=> Use `-dev` suffix in the versioning of the `sortition-pools`

.github/workflows/npm.yml
Fixing incorrectly configured job. There is no `solidity` folder in the
`sortition-pools` project. The `package.json` file resides in the
project's root directory.
=> Remove `working-directory` setting from the workflow

.github/workflows/npm.yml
Use of the `master` and `slave` terms in the computer industry is
widespread, but has been recently discouraged, as it was brought to
attention that the terms may be considered offensive.
GitHub has already moved their default repositories from the `master`
to `main` in many places. We're planning to do the same for our
repositories, this however requires some changes in the code.
After the proposed changes get merged to the `master` branch, the
repository should be ready for the migration from `master` to `main`.
To migrate from `master` to `main`:
1. Do a local branch rename with `git branch -m master main`
2. Push the renamed branch `git push -u origin main`
3. In the Github repo settings, rename the default branch: Settings ->
Branches -> Default branch -> (pencil icon) -> (change …
=> Migrate from `master` to `main` branch

contracts/Leaf.sol, contracts/SortitionTree.sol, test/sortitionTreeTest.js
`Leaf.make` expects ID to fit in 32 bits but we were not asserting anywhere
if this is really the case. From now on, when a new operator joins the
pool we check if the max capacity was not exceeded and we assert
whether ID fits in 32 bits and creation block fits in 64 bits.
Additionally, `getOperatorID` and `getIDOperator` functions operate now
on `uint32` officially. This is how the external code stores group
members data (see https://github.com/keep-network/keep-core/pull/2677) and it makes sense to
have public sortition pool API reflecting it, even though internally,
for gas efficiency purposes, sortition pool can work on `uint256` IDs.
Last but not least, I took an opportunity and added a function allowing to 
fetch operator addresses by their IDs in one call: `getIDOperators`. …
=> 32 bits: adjusted public API for operator ID, added bitlength checks

README.adoc
Updated README after removing bonded sortition pool and fully 
backed sortition pool. Also, the application is now responsible
for maintaining the state up-to-date, and operator weight is not
validated during the selection. Keeping the README minimal and
focused on the memory layout.
=> README update to reflect the most recent code state

contracts/SortitionPool.sol, contracts/SortitionPoolFactory.sol, contracts/SortitionPoolStub.sol, package-lock.json, package.json, test/sortitionPoolTest.js
The sortition pool owner should be able to transfer the pool ownership to someone else. The first use case is beacon v2 where `RandomBeacon` contract needs to be the owner of the sortition pool but, in the same time, accepts the pool as a constructor param. This way the right pool owner can not be set upon pool deployment.
=> Transfer ownership mechanism

contracts/SortitionPool.sol, test/sortitionPoolTest.js
Sortition pool should expose a way to enable and disable the locked state in which operators cannot be inserted, removed, and updated. The first use case is beacon v2 where `RandomBeacon` contract needs to lock the pool during group creation process.
=> Pool locking mechanism

contracts/Leaf.sol, contracts/SortitionPool.sol, contracts/SortitionPoolStub.sol, test/factoryTest.js
This change makes usage of `selectGroup` easier as operators are now represented by IDs. This change should reduce the number of `address <-> ID` conversions done by the client code.
=> Return operator IDs from `selectGroup`

contracts/SortitionPool.sol
The owner of the sortition pool needs to have a way to ban rewards for given operators and given period of time. During the ban, those operators are not eligible for rewards accounted due to pool participation.
=> Banning rewards stub

contracts/SortitionPool.sol, test/sortitionPoolTest.js
Depends on #135 
Refs https://github.com/keep-network/keep-core/issues/2715
Updates to the operator-related API needed to integrate with T staking contract.
Changes included:
- Update operator status using its address 
Instead of using operator id as a parameter we need to use operator
address. T staking contract calls
`authorizationIncreased(address operator, uint256 amount)`
on the authorized application so there is no point in going from
address to id, and then from id to address again.
- Remove operator from the pool using its address
Instead of using operator id as a parameter, we need to use operator
address. T staking contract calls
`authorizationDecreaseRequested(address operator, uint96 amount)`
on the authorized application when the given operator requests to
decrease its …
=> Updates to operator API

contracts/SortitionPool.sol, test/sortitionPoolTest.js
Everyone should be able to call `selectGroup` to confirm if DKG result
submitted is valid. This is especially important in the optimistic
mode when result is submitted without on-chain validation, and then
potentially challenged.
=> Removed onlyOwner modifier from selectGroup function

.github/workflows/lint.yml, .github/workflows/npm.yml, .github/workflows/solidity-test.yml
We have CI workflows scattered across various repositories. We try to keep their implementation as similar as possible. In this PR and the ones listed below we introduce a couple of changes which unify used solutions and fix small mistakes, such as:
* making tagging of published packages consistent
* passing `NPM_TOKEN` secret as variable instead of passing it by writing to file
* handling caching of npm/yarn dependencies via `setup-node` action
* adding `workflow_dispatch` job trigger where it's missing
* using Node.js in version 14.x instead of 12.x where possible
Related PRs in other repositories:
* https://github.com/keep-network/keep-core/pull/2776
* https://github.com/keep-network/keep-ecdsa/pull/941
* https://github.com/keep-network/tbtc/pull/842
* …
=> Unify CI workflows

package-lock.json, package.json
We're bumping up version of `@keep-network/sortition-pools` package from
`1.2.0-dev` to `2.0.0-dev`. This has been dictated by the fact that
there were recently major changes regarding sortition pools contracts -
many contracts have been removed and some new got added as well.
If this change gets accepted, we should consider removing packages from `1.2.0-dev.2` to `1.2.0-dev.25` from the npm registry, as they were improperly versioned (they should have been bumped up to `2.0.0-dev...`. After we remove them, we should close https://github.com/keep-network/keep-ecdsa/pull/943.
=> Bump up version to `2.0.0-dev`

.github/workflows/npm.yml, package.json
We'll be useing a `pre` tag for this package with contracts. We decided
to use 'dev` suffix for projects where we deploy contracts (and there is
a need for distinction between environments). Here we don't deploy
contracts, so we can use `pre` suffix/tag.
=> Use `pre` suffix & tag for npm package instead of `dev`

contracts/Rewards.sol, contracts/SortitionPool.sol, contracts/test/RewardsStub.sol, test/rewardsTest.js
Refs https://github.com/keep-network/keep-core/issues/2935
So far there was no function allowing to learn about the amount of
rewards available for withdrawal. Adding such function now.
=> Added function allowing to learn about the rewards available

contracts/SortitionPool.sol
~~Depends on https://github.com/keep-network/sortition-pools/pull/162; Please do not merge until #162 is not in `main`.~~
This allows to emit an event in application contract with the amount of
rewards withdrawn. It will be helpful for the dApp when rendering
rewards page.
=> SortitionPool.withdrawRewards returns the amount of rewards withdrawn 

test/sortitionPoolTest.js
Follow up to #163, we alter `test/sortitionPoolTest.js` to make assertions about the return values of `withdrawRewards`.
Unfortunately since `withdrawRewards` isn't a `view` function we have to extract the return data from the events or logs.
Tagging @pdyraga for review
=> Test the output of `SortitionPool.withdrawRewards`

test/rewardsTest.js
This PR annotates the rewards tests. These tests were already in a good spot and very explanatory, so I added additional context to help anyone reading the file.
Tagging @lukasz-zimnoch @eth-r and @pdyraga for review
refs https://github.com/keep-network/sortition-pools/issues/161
=> Annotate Rewards Tests

test/sortitionTreeTest.js
This PR overhauls the sortition tree tests!
Summary of changes:
+ Simplified the test layout (removed unnecessary `beforeEach` constructions)
+ Simplified the `position` constructions to make it more human-readable
+ Heavily annotated the tests
+ Added some additional specs where the assertions seemed sparse
It might be useful to review commit by commit
Tagging @eth-r @lukasz-zimnoch @pdyraga
=> Sortition Tree Tests

test/rngTest.js
This PR gives the RNG tests some love and care, adding generative testing where useful, as well as adding an assertion that the results from `getIndex` actually are uniform.
Tagging @pdyraga @eth-r @lukasz-zimnoch and @michalinacienciala for review
Refs #161
=> Overhaul the RNG tests

contracts/Rewards.sol, contracts/SortitionPool.sol, test/sortitionPoolTest.js
Refs https://github.com/keep-network/keep-core/issues/3008
The off-chain client can monitor the reward eligibility and restore it when the
time comes but it is easier for the client to use the operator address instead
of the operator ID.
Looking at the public API so far, the reward eligibility was getting restored
using the address so it makes sense to have all other reward-eligibility-related
functions use the operator address as well, for consistency.
=> Restore reward eligibility by operator address

contracts/Rewards.sol, test/sortitionPoolTest.js
We expect the pool weight to be non-zero so that we do not allocate rewards to
an empty pool. The condition checking `currentPoolWeight >= 0` was incorrect
given `== 0` case is exactly what we want to avoid. The transaction would fail
later on `totalAmount / currentPoolWeight` but human-readable revert was the
intention of this `require` check.
=> Fixed a check for non-zero weight when allocating rewards

README.md
We're adding a badge to the README file which shows the status of the workflow testing the Solidity code in the `sortition-pools` repository. The displayed status is based the status of the most recently executed `Test Solidity` workflow triggered by the cron.
Refs:
https://github.com/threshold-network/token-dashboard/pull/296
https://github.com/keep-network/coverage-pools/pull/218
https://github.com/keep-network/keep-common/pull/108
https://github.com/keep-network/keep-core/pull/3398
https://github.com/keep-network/tbtc-v2/pull/420
=> Add the status badge to README

README.md
The `shields.io` have changed the syntax of the endpoints generating status badges, resulting in showing false failure status when old syntax was used. Updating the READMEs to use the new syntax.
Read more: badges/shields#8671.
Refs:
https://github.com/keep-network/keep-common/pull/112
https://github.com/keep-network/keep-core/pull/3449
https://github.com/keep-network/tbtc-v2/pull/429
https://github.com/keep-network/coverage-pools/pull/221
=> Fix badges after change in shields.io syntax
